language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

repo_token: VDm4zSOaeNlATYux43bfEumzFoW1TAX87
gem 'coveralls', require: false
